#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Ensure the system is updated 
sudo apt-get -y update
sudo apt-get -y upgrade

# Install HAProxy
sudo apt-get -y install haproxy

# Add the required configuration and routing to my servers
echo "\
frontend proxynode
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    option forwardfor
    server web-01 34.207.156.226:80 check
    server web-02 54.90.63.216:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

# Make sure the service starts
sudo service haproxy restart
