#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

sudo apt-get -y update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
apt-get install -y haproxy=2.8.\*

echo "
backend web-backend
        balance roundrobin
        option forwardfor
        server 379713-web-01 34.207.156.226:80 check
        server 379713-web-02 54.90.63.216:80 check
frontend proxynode
        bind *:80
        mode http
        default_backend web-backend
" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable and start HAProxy service
sudo systemctl enable haproxy

# Make sure the service starts
sudo service haproxy start
