#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

ufw allow 1344
apt-get -y update
apt-get install -y haproxy

printf %s "
backend web-backend
        balance roundrobin
        option forwardfor
        server 9318-web-01 3.236.115.124:80 check
        server 9318-web-02 3.227.233.5:80 check
frontend proxynode
        bind *:80
        mode http
        default_backend web-backend
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
