#!/usr/bin/env bash
# install and configure apache to server "Hello Holberton"
sudo apt-get update
sudo apt-get install apache2
echo "Hello Holberton" | sudo tee /var/www/html/index.html > /dev/null
sudo chown www-data:www-data /var/www/html/index.html
sudo chmod 644 /var/www/html/index.html
sudo service apache2 restart
