#!/usr/bin/env bash
# conecting to a remote server with user and private key
# Server details
server_address="3.90.70.235"
user="ubuntu"
private_key="~/.ssh/school"

# SSH command with single-character flags
ssh -i $private_key $user@$server_address
